### ISSUE TITLE
Custom config not loaded

### ISSUE THREAD

**Issue by AydinHassan** [netz98/n98-magerun#242]
Hi, I'm running magerun from the root of a project. The setup is like so:

```
somesite
   |
   |---- n98-magerun.phar
   |---- .n98-magerun.yaml
   |---- htdocs
   |        |---- app
   |        |---- downloader
```

I'm trying to use magerun to install magento from a custom repository. So in the `.n98-magerun.yaml` file I have the following:

```
commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: my-magento-git-repository
        version: 1.8.0.0
        source:
          url: git@bitbucket.org:somerepo
          type: git
          reference: master   
```

Magerun doesn't seem to find or load the config. I'm not sure if it has something to do with the root folder. I've tried forcing the root folder with the following commands (in the root of the project, eg. `somesite`):

```
php n98-magerun.phar --root-dir=. install
php n98-magerun.phar --root-dir=htdocs install
```

However, that doesn't work either. Only the default packages are shown.

I also tried running from src using composer and I get a different issue here, when running from the root repository:

```
vendor/bin/n98-magerun
```

Result:
The "" directory does not exist.

I debugged and that message is thrown from [here](https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/ConfigurationLoader.php#L200)

The value passed to the ->in() method is always false!

Would be great if any of you guys to point me in the right direction with this.

I'm running Mac OSX 10.8.5 with MAMP. `/usr/bin/php` is linked to `/Applications/MAMP/bin/php/php5.3.27/bin/php`

Any more info just ask.
