### ISSUE TITLE
Changing values of numerically indexed yaml config arrays in ~/.n98-magerun.yaml

### ISSUE THREAD

**Issue by Vinai** [netz98/n98-magerun#431]
Usecase: I want to change the source archive URL for a magento or sample data package.

I tried to achieve that by placing the following code in the ~/.n98-magerun.yaml file:

```
commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      0:
        name: magento-ce-1.9.0.1
        extra:
          sample-data: compressed-sample-data-1.9.0.0
```

My intention is to change that value of `$this->commandConfig['magento-packages'][0]['extra']['sample-data']`.
However, that did not work. A new record is always added to the $this->commandConfig['magento-packages'] array, instead of overwriting a value of the record with the index 0.
This was the result:

```
$this->commandConfig['magento-packages'][12]['extra']['sample-data'] = 'compressed-sample-data-1.9.0.0';
```

Please note that the array index 12 was added instead of overwriting a value within the index 0.

Is there some way to achieve this?
