### ISSUE TITLE
Table-groups could not be resolved

### ISSUE THREAD

**Issue by danemacmillan** [netz98/n98-magerun#470]
I'm using the db:dump option with a custom table group, defined in `app/etc/n98-magerun.yaml`. It looks like this:

```
commands:
  N98\Magento\Command\Database\DumpCommand:
    table-groups:
      - id: mygroup
        description: Strip all tables for development
        tables: @log @dataflowtemp @stripped @sales @customers @trade @development @search v_ea_product_summary tag tag_relation tag_summary wishlist report_event report_viewed_product_index report_compared_product_index newsletter_subscriber aw_advancednewsletter_subscriber ugiftcert_* catalog_product_flat_* catalog_category_flat_*
```
For some reason it's outputting this error message:

```
DEBUG

  Dump MySQL Database

  [Exception]
  Table-groups could not be resolved: @search

Exception trace:
 () at /vagrant/sites/develop/vendor/n98/magerun/src/N98/Magento/Command/Database/DumpCommand.php:121
 N98\Magento\Command\Database\DumpCommand->resolveTables() at /vagrant/sites/develop/vendor/n98/magerun/src/N98/Magento/Command/Database/DumpCommand.php:125
 N98\Magento\Command\Database\DumpCommand->resolveTables() at /vagrant/sites/develop/vendor/n98/magerun/src/N98/Magento/Command/Database/DumpCommand.php:171
 N98\Magento\Command\Database\DumpCommand->execute() at /vagrant/sites/develop/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at /vagrant/sites/develop/vendor/symfony/console/Symfony/Component/Console/Application.php:887
 Symfony\Component\Console\Application->doRunCommand() at /vagrant/sites/develop/vendor/symfony/console/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /vagrant/sites/develop/vendor/n98/magerun/src/N98/Magento/Application.php:456
 N98\Magento\Application->doRun() at /vagrant/sites/develop/vendor/symfony/console/Symfony/Component/Console/Application.php:121
 Symfony\Component\Console\Application->run() at /vagrant/sites/develop/vendor/n98/magerun/src/N98/Magento/Application.php:536
 N98\Magento\Application->run() at /vagrant/sites/develop/vendor/n98/magerun/bin/n98-magerun:5


db:dump [-t|--add-time[="..."]] [-c|--compression="..."] [--only-command] [--print-only-filename] [--no-single-transaction] [--human-readable] [--stdout] [-s|--strip[="..."]] [-f|--force] [filename]
```

Edit: I should mention that this typically works on other machines. Oddly, not on the one that resulted in this error.
