### ISSUE TITLE
How to use installer with local archives

### ISSUE THREAD

**Issue by joh-klein** [netz98/n98-magerun#479]
How can I provide already downloaded archives of magento/magento-sample-data without having them accessible via an URL? Can't I just provide the path in the ~/.n98-magerun.yaml?

**Comment by cmuench** [comment]
Currently it's not possible to replace the path over config. See #431 for the issue.
As workaround it's possible to add your own URLs.
URLs can have schema "file://".

Tested setup on my machine:

```
commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: my-tarball-installation
        version: 1.9.1.0
        dist:
          url: file:///home/cmuench/magento-1.9.1.0.tar.gz
          type: tar 
        extra:
          sample-data: my-sample-data-1.9.1.0

    demo-data-packages:
      - name: my-sample-data-1.9.1.0
        version: 1.9.1.0
        dist:
          url: file:///home/cmuench/my-sample-data-1.9.1.0.tar.gz
          type: tar 
```
