### ISSUE TITLE
Issue: memory cap

### ISSUE THREAD

**Issue by gregorskii** [netz98/n98-magerun#582]
Hi there,

I am receiving this error while using MAMP Pro PHP 5.6.7.

I am running the command n98-magerun.phar install on version 1.96.1on Mac OSX.

Using this command:

```
n98-magerun.phar install \
    --magentoVersionByName="magento-ce-1.9.1.1" \
    --dbHost="/Applications/MAMP/tmp/mysql/mysql.sock" \
    --dbUser=${DEV_DB_USER} \
    --dbPass=${DEV_DB_PASSWORD} \
    --dbName=${DEV_DB_NAME} \
    --installSampleData=no \
    --installationFolder="magento" \
    --baseUrl=${BASE_URL}

```

And this config:

```

commands:
  N98\Magento\Command\Installer\InstallCommand:
    installation:
      defaults:
        currency: USD
        locale: en_US
        timezone: America/Los_Angeles
        use_secure: no
        use_rewrites: yes
        session_save: files

```

```
[09-Jun-2015 06:55:50 Europe/Berlin] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32769 bytes) in phar:///usr/local/bin/n98-magerun.phar/vendor/composer/composer/src/Composer/Downloader/TarDownloader.php on line 28
```

I have tried increasing the memory size in MAMP to 512 MB but it does not seem to have any affect.

Is this issue common?

Thanks
