### ISSUE TITLE
Sample data from Git?

### ISSUE THREAD

**Issue by frozenminds** [netz98/n98-magerun#587]
Hello,

I have a private repository where I store sample data. Is there a way to configure Magerun to download and install the sample data from the repo? I've tried it now with the latest phar and it doesn't work.

Here's an example of my `.n98-magerun.yaml`:

```
commands:
  N98\Magento\Command\Installer\InstallCommand:

    demo-data-packages:
      - name: magento-custom-sample-data-0.1.0.0
        version: 0.1.0.0
        source:
          url: git@myrepo:magento/sample-data.git
          type: git
          reference: 0.1.0.0
```

Each version lives in it's on tag on Git.

Thank you in advance!

**Comment by cmuench** [comment]
@frozenminds It's not possible to replace the current configured sample data according to config merge process (see issue #431).
If you specify own sample data you need also to specify own Magento versions. The download urls could be the save.
A good blog post about that can be found here: https://plugin.company/blog/creating-local-magento-repository-n98-magerun/

**Comment by frozenminds** [comment]
Hi @cmuench,

I do not try to replace anything.

Actually I have a custom repository for custom Magento versions and another repository for custom sample datas. Works perfectly for the Magento installation and repo.
However it does not work if I specify for the sample data a repository, only if I configure a downloadable link to a `tar.gz`. I thought it could be possible to download and install sample data from a Git tag also.

Or am I missing something?

Works with this:
```
dist:
    url: http://myrepo.com/magento/sample-data/magento-sample-data-6b6d24e56509bbf4df8bcfa67c6ba82dd5625c3b.tar.gz
    type: tar
```

but it does NOT with this:
```
source:
   url: git@myrepo:magento/sample-data.git
    type: git
   reference: 0.1.0.0
```

Thank you!
