### ISSUE TITLE
install from local source

### ISSUE THREAD

**Issue by arosenhagen** [netz98/n98-magerun#726]
This is a follow-up to #615
Unfortunately local file declarations (file:// or POSIX) in .n98-magerun-yaml doesn't work as mentioned by @tkn98. The error thrown is:
```
Downloader "Composer\Downloader\TarDownloader" is a dist type downloader and can not be used to download source
```
Would be nice if we find a way to feed the install command with a file on the local file system. This way we can use magedownload-cli prior to install the official files.

**Comment by ktomk** [comment]
Can you please add an example how the yaml looks like in your case? That should help reproducing the issue.

**Comment by arosenhagen** [comment]
sure, the following is my yaml in this case:
```
commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: magento-ce-1.9.2.2
        version: 1.9.2.2
        source:
          url: /tmp/magento-ce-1.9.2.2.tar.gz
          type: tar
          shasum: c213fc9c375241fd52525f47fd68774e8a73e851
```

**Comment by arosenhagen** [comment]
confirmed. just for future reference - the following works for local files:
```
commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: magento-ce-1.9.2.2
        version: 1.9.2.2
        dist:
          url: /tmp/magento-ce-1.9.2.2.tar.gz
          type: tar
          shasum: c213fc9c375241fd52525f47fd68774e8a73e851
```
