### ISSUE TITLE
Namespace clash between local and system modules

### ISSUE THREAD

**Issue by gwillem** [netz98/n98-magerun#861]
When local (in `~/.n98-magerun`) and system modules (in `/usr/local/share/n98-magerun`) have the same namespace defined in `n98-magerun.yaml`, I would expect that one of them (ideally, the one in the homedir) takes precedence. However, this is not the case in the situation that the system yaml defines a command that has no corresponding path in `~/.n98-magerun`. 

Effectively, this breaks local installations when modules are installed globally. 

```
$ magerun
PHP Fatal error:  Uncaught Error: Class 'Elgentos\Magento\Command\Media\Images\CleanCacheCommand' not found in phar:///usr/local/bin/n98-magerun/src/N98/Magento/Application.php:330
Stack trace:
#0 phar:///usr/local/bin/n98-magerun/src/N98/Magento/Application.php(719): N98\Magento\Application->registerCustomCommands()
#1 phar:///usr/local/bin/n98-magerun/src/N98/Magento/Application.php(663): N98\Magento\Application->init(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /usr/local/bin/n98-magerun(8): N98\Magento\Application->run()
#3 {main}
  thrown in phar:///usr/local/bin/n98-magerun/src/N98/Magento/Application.php on line 330
```

~/.n98-magerun/modules/magerun-addons/n98-magerun.yaml:

```
autoloaders:
  Elgentos: %module%/src

commands:
  customCommands:
    - Elgentos\Magento\Command\System\Store\Config\BaseUrlSetCommand
    - Elgentos\Magento\Command\Media\SyncCommand
    - Elgentos\Magento\Command\Extension\TranslationsCommand
    - Elgentos\Magento\Command\Dev\TemplateVars
    - Elgentos\Magento\Command\Dev\OldAdminRouting
    - Elgentos\Magento\Command\Dev\Events\ListCommand
    - Elgentos\Magento\Command\Dev\Events\FireCommand
    - Elgentos\Magento\Command\Dev\Events\ListenCommand
    - Elgentos\Magento\Command\Customer\CleanTaxvatCommand
    - Elgentos\Magento\Command\System\Url\Rewrites\ExportCommand
    - Elgentos\Magento\Command\Media\Images\CleanTablesCommand
    - Elgentos\Magento\Command\Media\Images\DefaultImageCommand
    - Elgentos\Magento\Command\Media\Images\RemoveDuplicatesCommand
    - Elgentos\Magento\Command\Media\Images\RemoveOrphansCommand
    - Elgentos\Magento\Command\Dev\PossibleSqlInjection
```

/usr/local/share/n98-magerun/modules/Elgentos/n98-magerun.yaml 

```
autoloaders:
  Elgentos: %module%/src

commands:
  customCommands:
    - Elgentos\Magento\Command\System\Store\Config\BaseUrlSetCommand
    - Elgentos\Magento\Command\Media\SyncCommand
    - Elgentos\Magento\Command\Extension\TranslationsCommand
    - Elgentos\Magento\Command\Dev\TemplateVars
    - Elgentos\Magento\Command\Dev\OldAdminRouting
    - Elgentos\Magento\Command\Dev\Events\ListCommand
    - Elgentos\Magento\Command\Dev\Events\FireCommand
    - Elgentos\Magento\Command\Dev\Events\ListenCommand
    - Elgentos\Magento\Command\Customer\CleanTaxvatCommand
    - Elgentos\Magento\Command\System\Url\Rewrites\ExportCommand
    - Elgentos\Magento\Command\Media\Images\CleanTablesCommand
    - Elgentos\Magento\Command\Media\Images\CleanCacheCommand
    - Elgentos\Magento\Command\Media\Images\DefaultImageCommand
    - Elgentos\Magento\Command\Media\Images\RemoveDuplicatesCommand
    - Elgentos\Magento\Command\Media\Images\RemoveOrphansCommand
    - Elgentos\Magento\Command\Dev\PossibleSqlInjection
```

Note that the system yaml has a new command (CleanCacheCommand) (cc @peterjaap)
